AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Triggered by S3, indexes faces against a collection in Amazon Rekognition'
Resources:
  IndexFacesFaceRecognitionService:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: >-
        Triggered by S3, indexes faces against a collection in Amazon
        Rekognition
      MemorySize: 128
      Timeout: 5
      Role: >-
        arn:aws:iam::468780546504:role/Face-Recognition-Service-LambdaExecutionRole-1E42GBGKV8XW9
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: index/
  Bucket1:
    Type: 'AWS::S3::Bucket'
